# Nome do Workflow
name: Exemplo de fluxo de trabalho

# Execução manual
on:
  workflow_dispatch:

jobs:
  acao_inicial_job: 
    runs-on: ubuntu-lates
    steps: 
      - name: imprime ola
        run: echo "OLA"
      - name: Imprime Xau
        run: echo "xau"
